"""Deploy and Advanced Features routes for Assistant Melus"""
from fastapi import APIRouter, HTTPException, Request
from typing import Optional
import logging
import os
import json
import zipfile
import io
from pathlib import Path

from utils import generate_id, utc_now, get_authenticated_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/deploy", tags=["deploy"])


@router.post("/prepare")
async def prepare_deployment(request: Request):
    """Prepare a project for deployment - generates all necessary files"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    body = await request.json()
    project_id = body.get("project_id")
    
    if not project_id:
        raise HTTPException(status_code=400, detail="project_id required")
    
    # Get project
    project = await db.projects.find_one(
        {"project_id": project_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Collect all files from agent results
    files = []
    for result in project.get("agent_results", []):
        agent_result = result.get("result", {})
        if "files" in agent_result:
            for f in agent_result["files"]:
                files.append({
                    "path": f.get("path", "unknown"),
                    "content": f.get("content", ""),
                    "agent": result.get("agent", "unknown")
                })
    
    # Generate deployment configuration
    deploy_config = {
        "project_name": project.get("name", "app"),
        "version": "1.0.0",
        "files": files,
        "deployment_ready": True
    }
    
    # Update project with deployment info
    await db.projects.update_one(
        {"project_id": project_id},
        {
            "$set": {
                "deployment_config": deploy_config,
                "deployment_status": "prepared",
                "updated_at": utc_now()
            }
        }
    )
    
    return {
        "status": "prepared",
        "project_id": project_id,
        "files_count": len(files),
        "deployment_config": deploy_config
    }


@router.post("/download-zip")
async def download_project_zip(request: Request):
    """Generate and return a ZIP file with all project code"""
    from fastapi.responses import StreamingResponse
    
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    body = await request.json()
    project_id = body.get("project_id")
    
    if not project_id:
        raise HTTPException(status_code=400, detail="project_id required")
    
    # Get project
    project = await db.projects.find_one(
        {"project_id": project_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        # Add README
        readme_content = f"""# {project.get('name', 'Generated App')}

## Description
{project.get('description', 'Generated by Assistant Melus')}

## Generated Files
This project was generated using Assistant Melus AI-powered app generator.

## Setup
1. Install dependencies
2. Configure environment variables
3. Run the application

## Credits
Generated on {utc_now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        zip_file.writestr("README.md", readme_content)
        
        # Add all files from agent results
        for result in project.get("agent_results", []):
            agent_result = result.get("result", {})
            if "files" in agent_result:
                for f in agent_result["files"]:
                    file_path = f.get("path", "unknown.txt")
                    file_content = f.get("content", "")
                    zip_file.writestr(file_path, file_content)
        
        # Add package.json if frontend files exist
        has_frontend = any(
            "frontend" in r.get("agent", "") or ".jsx" in str(r.get("result", {}).get("files", []))
            for r in project.get("agent_results", [])
        )
        
        if has_frontend:
            package_json = {
                "name": project.get("name", "app").lower().replace(" ", "-"),
                "version": "1.0.0",
                "private": True,
                "dependencies": {
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0",
                    "react-router-dom": "^6.0.0"
                },
                "scripts": {
                    "start": "react-scripts start",
                    "build": "react-scripts build"
                }
            }
            zip_file.writestr("frontend/package.json", json.dumps(package_json, indent=2))
        
        # Add requirements.txt if backend files exist
        has_backend = any(
            "backend" in r.get("agent", "") or ".py" in str(r.get("result", {}).get("files", []))
            for r in project.get("agent_results", [])
        )
        
        if has_backend:
            requirements = """fastapi>=0.100.0
uvicorn>=0.23.0
motor>=3.0.0
pydantic>=2.0.0
python-dotenv>=1.0.0
"""
            zip_file.writestr("backend/requirements.txt", requirements)
    
    zip_buffer.seek(0)
    
    # Update project download count
    await db.projects.update_one(
        {"project_id": project_id},
        {
            "$inc": {"download_count": 1},
            "$set": {"last_downloaded": utc_now()}
        }
    )
    
    filename = f"{project.get('name', 'project').replace(' ', '_')}.zip"
    
    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.post("/redeploy")
async def redeploy_project(request: Request):
    """Trigger a redeploy of a project/conversation"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    REDEPLOY_COST = 50
    
    if user_doc["credits"] < REDEPLOY_COST:
        raise HTTPException(status_code=402, detail="Créditos insuficientes para redeploy")
    
    body = await request.json()
    project_id = body.get("project_id")
    conversation_id = body.get("conversation_id")
    
    target_id = project_id or conversation_id
    if not target_id:
        raise HTTPException(status_code=400, detail="project_id or conversation_id required")
    
    # Create deployment record
    deployment_id = generate_id("deploy")
    deployment = {
        "deployment_id": deployment_id,
        "user_id": user_id,
        "project_id": project_id,
        "conversation_id": conversation_id,
        "status": "in_progress",
        "started_at": utc_now(),
        "completed_at": None,
        "logs": [
            {"timestamp": utc_now().isoformat(), "message": "Deployment initiated"},
            {"timestamp": utc_now().isoformat(), "message": "Building application..."},
            {"timestamp": utc_now().isoformat(), "message": "Configuring environment..."}
        ]
    }
    await db.deployments.insert_one(deployment)
    
    # Deduct credits
    new_credits = user_doc["credits"] - REDEPLOY_COST
    await db.users.update_one(
        {"user_id": user_id},
        {
            "$set": {"credits": new_credits},
            "$inc": {"credits_used": REDEPLOY_COST}
        }
    )
    
    # Log usage
    await db.agent_usage.insert_one({
        "usage_id": generate_id("usage"),
        "user_id": user_id,
        "agent_type": "deploy",
        "credits_used": REDEPLOY_COST,
        "project_id": project_id,
        "conversation_id": conversation_id,
        "created_at": utc_now()
    })
    


@router.post("/vercel")
async def deploy_to_vercel(request: Request):
    """Deploy workspace to Vercel - Generates deployment package"""
    import aiohttp
    
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    # Check credits
    is_unlimited = user_doc.get("unlimited_credits", False) or user_doc.get("is_owner", False)
    DEPLOY_COST = 100  # 100 credits for Vercel deploy
    
    if not is_unlimited and user_doc.get("credits", 0) < DEPLOY_COST:
        raise HTTPException(status_code=402, detail=f"Necesitas {DEPLOY_COST} créditos para desplegar en Vercel")
    
    body = await request.json()
    workspace_id = body.get("workspace_id")
    project_name = body.get("project_name", "melus-app")
    
    if not workspace_id:
        raise HTTPException(status_code=400, detail="workspace_id required")
    
    # Get workspace
    workspace = await db.workspaces.find_one(
        {"workspace_id": workspace_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not workspace:
        raise HTTPException(status_code=404, detail="Workspace not found")
    
    workspace_files = workspace.get("files", {})
    if not workspace_files:
        raise HTTPException(status_code=400, detail="No hay archivos para desplegar")
    
    # For Vercel, we need to prepare the project structure
    # Since we don't have direct Vercel API integration yet,
    # we'll generate a deployment-ready ZIP that can be uploaded manually
    
    # Create vercel.json configuration
    vercel_config = {
        "version": 2,
        "name": project_name.lower().replace(" ", "-"),
        "builds": [
            {"src": "package.json", "use": "@vercel/static-build", "config": {"distDir": "build"}}
        ],
        "routes": [
            {"handle": "filesystem"},
            {"src": "/(.*)", "dest": "/index.html"}
        ]
    }
    
    # Create deployment record
    deployment_id = generate_id("dep")
    
    deployment = {
        "deployment_id": deployment_id,
        "workspace_id": workspace_id,
        "user_id": user_id,
        "platform": "vercel",
        "project_name": project_name,
        "status": "ready_for_upload",
        "files_count": len(workspace_files),
        "vercel_config": vercel_config,
        "created_at": utc_now(),
        "instructions": [
            "1. Descarga el archivo ZIP del proyecto",
            "2. Ve a https://vercel.com/new",
            "3. Arrastra la carpeta del proyecto o conecta tu GitHub",
            "4. Vercel detectará automáticamente la configuración",
            "5. Haz clic en 'Deploy'"
        ]
    }
    
    await db.deployments.insert_one(deployment)
    
    # Update workspace
    await db.workspaces.update_one(
        {"workspace_id": workspace_id},
        {
            "$set": {
                "vercel_ready": True,
                "last_deployment_id": deployment_id,
                "updated_at": utc_now()
            }
        }
    )
    
    # Deduct credits
    if not is_unlimited:
        await db.users.update_one(
            {"user_id": user_id},
            {
                "$inc": {"credits": -DEPLOY_COST, "credits_used": DEPLOY_COST}
            }
        )
    
    return {
        "deployment_id": deployment_id,
        "status": "ready_for_upload",
        "platform": "vercel",
        "vercel_config": vercel_config,
        "instructions": deployment["instructions"],
        "download_url": f"/api/deploy/download-workspace-zip?workspace_id={workspace_id}",
        "credits_used": 0 if is_unlimited else DEPLOY_COST
    }


@router.get("/download-workspace-zip")
async def download_workspace_zip(request: Request):
    """Generate and return a ZIP file with workspace code ready for Vercel"""
    from fastapi.responses import StreamingResponse
    
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    workspace_id = request.query_params.get("workspace_id")
    
    if not workspace_id:
        raise HTTPException(status_code=400, detail="workspace_id required")
    
    # Get workspace
    workspace = await db.workspaces.find_one(
        {"workspace_id": workspace_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not workspace:
        raise HTTPException(status_code=404, detail="Workspace not found")
    
    workspace_files = workspace.get("files", {})
    
    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    project_name = workspace.get("name", "app").lower().replace(" ", "-")
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        # Add README
        readme_content = f"""# {workspace.get('name', 'Generated App')}

## Descripción
{workspace.get('description', 'Aplicación generada con Melus AI')}

## Desplegar en Vercel

### Opción 1: CLI
```bash
npm install -g vercel
vercel login
vercel --prod
```

### Opción 2: Dashboard
1. Ve a https://vercel.com/new
2. Arrastra esta carpeta
3. Haz clic en Deploy

## Instalación Local
```bash
npm install
npm start
```

## Tecnologías
- React 18
- React Router v6
- Tailwind CSS

---
Generado por [Melus AI](https://melusai.com)
"""
        zip_file.writestr(f"{project_name}/README.md", readme_content)
        
        # Add vercel.json
        vercel_config = json.dumps({
            "version": 2,
            "name": project_name,
            "builds": [
                {"src": "package.json", "use": "@vercel/static-build", "config": {"distDir": "build"}}
            ],
            "routes": [
                {"handle": "filesystem"},
                {"src": "/(.*)", "dest": "/index.html"}
            ]
        }, indent=2)
        zip_file.writestr(f"{project_name}/vercel.json", vercel_config)
        
        # Add all workspace files
        for file_path, content in workspace_files.items():
            zip_file.writestr(f"{project_name}/{file_path}", content)
        
        # Ensure package.json has build script
        if "package.json" in workspace_files:
            try:
                pkg = json.loads(workspace_files["package.json"])
                if "scripts" not in pkg:
                    pkg["scripts"] = {}
                pkg["scripts"]["build"] = "react-scripts build"
                pkg["scripts"]["start"] = "react-scripts start"
                pkg["dependencies"]["react-scripts"] = "^5.0.1"
                zip_file.writestr(f"{project_name}/package.json", json.dumps(pkg, indent=2))
            except:
                pass
    
    zip_buffer.seek(0)
    
    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f'attachment; filename="{project_name}.zip"'
        }
    )

    # Simulate deployment completion (in production, this would trigger actual deployment)
    await db.deployments.update_one(
        {"deployment_id": deployment_id},
        {
            "$set": {
                "status": "completed",
                "completed_at": utc_now()
            },
            "$push": {
                "logs": {
                    "timestamp": utc_now().isoformat(),
                    "message": "Deployment completed successfully"
                }
            }
        }
    )
    
    return {
        "deployment_id": deployment_id,
        "status": "completed",
        "message": "Redeploy completado exitosamente",
        "credits_used": REDEPLOY_COST,
        "credits_remaining": new_credits
    }


@router.get("/status/{deployment_id}")
async def get_deployment_status(request: Request, deployment_id: str):
    """Get deployment status"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    deployment = await db.deployments.find_one(
        {"deployment_id": deployment_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not deployment:
        raise HTTPException(status_code=404, detail="Deployment not found")
    
    return deployment


@router.get("/history")
async def get_deployment_history(request: Request):
    """Get user's deployment history"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    deployments = await db.deployments.find(
        {"user_id": user_id},
        {"_id": 0}
    ).sort("started_at", -1).limit(20).to_list(20)
    
    return {"deployments": deployments}
