"""Deploy and Advanced Features routes for Assistant Melus"""
from fastapi import APIRouter, HTTPException, Request
from typing import Optional
import logging
import os
import json
import zipfile
import io
from pathlib import Path

from utils import generate_id, utc_now, get_authenticated_user

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/deploy", tags=["deploy"])


@router.post("/prepare")
async def prepare_deployment(request: Request):
    """Prepare a project for deployment - generates all necessary files"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    body = await request.json()
    project_id = body.get("project_id")
    
    if not project_id:
        raise HTTPException(status_code=400, detail="project_id required")
    
    # Get project
    project = await db.projects.find_one(
        {"project_id": project_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Collect all files from agent results
    files = []
    for result in project.get("agent_results", []):
        agent_result = result.get("result", {})
        if "files" in agent_result:
            for f in agent_result["files"]:
                files.append({
                    "path": f.get("path", "unknown"),
                    "content": f.get("content", ""),
                    "agent": result.get("agent", "unknown")
                })
    
    # Generate deployment configuration
    deploy_config = {
        "project_name": project.get("name", "app"),
        "version": "1.0.0",
        "files": files,
        "deployment_ready": True
    }
    
    # Update project with deployment info
    await db.projects.update_one(
        {"project_id": project_id},
        {
            "$set": {
                "deployment_config": deploy_config,
                "deployment_status": "prepared",
                "updated_at": utc_now()
            }
        }
    )
    
    return {
        "status": "prepared",
        "project_id": project_id,
        "files_count": len(files),
        "deployment_config": deploy_config
    }


@router.post("/download-zip")
async def download_project_zip(request: Request):
    """Generate and return a ZIP file with all project code"""
    from fastapi.responses import StreamingResponse
    
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    body = await request.json()
    project_id = body.get("project_id")
    
    if not project_id:
        raise HTTPException(status_code=400, detail="project_id required")
    
    # Get project
    project = await db.projects.find_one(
        {"project_id": project_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not project:
        raise HTTPException(status_code=404, detail="Project not found")
    
    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        # Add README
        readme_content = f"""# {project.get('name', 'Generated App')}

## Description
{project.get('description', 'Generated by Assistant Melus')}

## Generated Files
This project was generated using Assistant Melus AI-powered app generator.

## Setup
1. Install dependencies
2. Configure environment variables
3. Run the application

## Credits
Generated on {utc_now().strftime('%Y-%m-%d %H:%M:%S')}
"""
        zip_file.writestr("README.md", readme_content)
        
        # Add all files from agent results
        for result in project.get("agent_results", []):
            agent_result = result.get("result", {})
            if "files" in agent_result:
                for f in agent_result["files"]:
                    file_path = f.get("path", "unknown.txt")
                    file_content = f.get("content", "")
                    zip_file.writestr(file_path, file_content)
        
        # Add package.json if frontend files exist
        has_frontend = any(
            "frontend" in r.get("agent", "") or ".jsx" in str(r.get("result", {}).get("files", []))
            for r in project.get("agent_results", [])
        )
        
        if has_frontend:
            package_json = {
                "name": project.get("name", "app").lower().replace(" ", "-"),
                "version": "1.0.0",
                "private": True,
                "dependencies": {
                    "react": "^18.2.0",
                    "react-dom": "^18.2.0",
                    "react-router-dom": "^6.0.0"
                },
                "scripts": {
                    "start": "react-scripts start",
                    "build": "react-scripts build"
                }
            }
            zip_file.writestr("frontend/package.json", json.dumps(package_json, indent=2))
        
        # Add requirements.txt if backend files exist
        has_backend = any(
            "backend" in r.get("agent", "") or ".py" in str(r.get("result", {}).get("files", []))
            for r in project.get("agent_results", [])
        )
        
        if has_backend:
            requirements = """fastapi>=0.100.0
uvicorn>=0.23.0
motor>=3.0.0
pydantic>=2.0.0
python-dotenv>=1.0.0
"""
            zip_file.writestr("backend/requirements.txt", requirements)
    
    zip_buffer.seek(0)
    
    # Update project download count
    await db.projects.update_one(
        {"project_id": project_id},
        {
            "$inc": {"download_count": 1},
            "$set": {"last_downloaded": utc_now()}
        }
    )
    
    filename = f"{project.get('name', 'project').replace(' ', '_')}.zip"
    
    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )


@router.post("/redeploy")
async def redeploy_project(request: Request):
    """Trigger a redeploy of a project/conversation"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    REDEPLOY_COST = 50
    
    if user_doc["credits"] < REDEPLOY_COST:
        raise HTTPException(status_code=402, detail="Créditos insuficientes para redeploy")
    
    body = await request.json()
    project_id = body.get("project_id")
    conversation_id = body.get("conversation_id")
    
    target_id = project_id or conversation_id
    if not target_id:
        raise HTTPException(status_code=400, detail="project_id or conversation_id required")
    
    # Create deployment record
    deployment_id = generate_id("deploy")
    deployment = {
        "deployment_id": deployment_id,
        "user_id": user_id,
        "project_id": project_id,
        "conversation_id": conversation_id,
        "status": "in_progress",
        "started_at": utc_now(),
        "completed_at": None,
        "logs": [
            {"timestamp": utc_now().isoformat(), "message": "Deployment initiated"},
            {"timestamp": utc_now().isoformat(), "message": "Building application..."},
            {"timestamp": utc_now().isoformat(), "message": "Configuring environment..."}
        ]
    }
    await db.deployments.insert_one(deployment)
    
    # Deduct credits
    new_credits = user_doc["credits"] - REDEPLOY_COST
    await db.users.update_one(
        {"user_id": user_id},
        {
            "$set": {"credits": new_credits},
            "$inc": {"credits_used": REDEPLOY_COST}
        }
    )
    
    # Log usage
    await db.agent_usage.insert_one({
        "usage_id": generate_id("usage"),
        "user_id": user_id,
        "agent_type": "deploy",
        "credits_used": REDEPLOY_COST,
        "project_id": project_id,
        "conversation_id": conversation_id,
        "created_at": utc_now()
    })
    
    # Simulate deployment completion (in production, this would trigger actual deployment)
    await db.deployments.update_one(
        {"deployment_id": deployment_id},
        {
            "$set": {
                "status": "completed",
                "completed_at": utc_now()
            },
            "$push": {
                "logs": {
                    "timestamp": utc_now().isoformat(),
                    "message": "Deployment completed successfully"
                }
            }
        }
    )
    
    return {
        "deployment_id": deployment_id,
        "status": "completed",
        "message": "Redeploy completado exitosamente",
        "credits_used": REDEPLOY_COST,
        "credits_remaining": new_credits
    }


@router.get("/status/{deployment_id}")
async def get_deployment_status(request: Request, deployment_id: str):
    """Get deployment status"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    deployment = await db.deployments.find_one(
        {"deployment_id": deployment_id, "user_id": user_id},
        {"_id": 0}
    )
    
    if not deployment:
        raise HTTPException(status_code=404, detail="Deployment not found")
    
    return deployment


@router.get("/history")
async def get_deployment_history(request: Request):
    """Get user's deployment history"""
    db = request.app.state.db
    user_doc = await get_authenticated_user(request, db)
    user_id = user_doc["user_id"]
    
    deployments = await db.deployments.find(
        {"user_id": user_id},
        {"_id": 0}
    ).sort("started_at", -1).limit(20).to_list(20)
    
    return {"deployments": deployments}
